name: Send Mail
on: push

jobs:
 Mails:
  runs-on: ubuntu-latest
  
  steps: 
  - name: Send the New Mail
    run: echo "To Send the Mail by Using Git Hub Action"

  - name: By Using GitAction Workplace
    if: ${{ always() }}
    uses: dawidd6/acttion-send-mail@v3
    with:
      server_adress: smtp.gmail.com
      server_port: 465

      Username: ${{ secrets.EMAIL_USERNAME }}
      Password: ${{ secrets.EMAIL_PASSWORD }}

      subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
      body: ${{ github.workflow }} job of ${{ github.repository }} has completed with status ${{ job.status }}
      to: yogeshlc021@gmail.com
      from: Yogesh 